---
version: "3.4"
services:
  tools:
    tty: true
    volumes:
    # Bind mount the dev-tools directory to the container
      - type: bind
        source: ./
        target: "/opt/${PROJECT}/environment/"
    # Bind mount also the project folder to the container
      - type: bind
        source: "${DEV_WORKING_DIR}"
        target: "/opt/${PROJECT}/project/"
    # Build the container from the Dockerfile before we run it
    build:
      context: .
      dockerfile: ./Dockerfile
      # Ensure that Dockerfile has access to required vars
      # from .env file during build
      args:
        - PROJECT=$PROJECT
    network_mode: "bridge"
    image: "${PROJECT}"
    container_name: "${PROJECT}-env"

    # volumes:
    #   - ".:/app"
    #   - "~/.ssh:/home/ubuntu/.ssh"
    # Add your .aws or .azure or .kube directories here
    # - "$AZURE_CONFIG_DIR:/home/ubuntu/.azure"